Repository supershy42/chat, pull requests merged in 2024-12, with the labels that each got.

#1 웹소켓 채팅 프로토타입 구현
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/refactoring.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  .gitignore
  .gitmessage.txt
  Dockerfile
  chat_app/__init__.py
  chat_app/admin.py
  chat_app/apps.py
  chat_app/consumers.py
  chat_app/models.py
  chat_app/routing.py
  chat_app/serializers.py
  chat_app/services.py
  chat_app/tests.py
  chat_app/urls.py
  chat_app/views.py
  config/__init__.py
  config/asgi.py
  config/settings.py
  config/urls.py
  config/wsgi.py
  manage.py
  requirements.txt
Labels: feature

#4 CustomMiddleware 추가
  chat_app/tests.py
  config/asgi.py
  config/middlewares.py
  config/settings.py
  requirements.txt
Labels: feature

#5 ChatConsumer에서 유저 검증 로직 추가
  chat_app/consumers.py
  chat_app/migrations/0001_initial.py
  chat_app/migrations/__init__.py
  chat_app/serializers.py
  chat_app/services.py
  chat_app/tests/test_consumers.py
  chat_app/tests/tests.py
  config/asgi.py
  config/middleware.py
  config/settings.py
  requirements.txt
Labels: feature

#7 Save chat messages
  chat_app/close_codes.py
  chat_app/consumers.py
  chat_app/models.py
  chat_app/serializers.py
  chat_app/services.py
  chat_app/tests/__init__.py
  chat_app/tests/test_consumers.py
  chat_app/tests/tests.py
  chat_app/views.py
  config/middleware.py
  config/settings.py
  requirements.txt
Labels: feature

#8 ChatRoomMessageListView 구현
  chat_app/consumers.py
  chat_app/migrations/0002_remove_chatroom_last_message_and_more.py
  chat_app/serializers.py
  chat_app/services.py
  chat_app/tests/tests.py
  chat_app/urls.py
  chat_app/views.py
  config/settings.py
  requirements.txt
Labels: feature

#10 채팅방 삭제 기능 구현
  chat_app/services.py
  chat_app/urls.py
  chat_app/views.py
  config/services.py
Labels: feature

#12 Websocket 연결 시 토큰 전달 방식 변경
  config/middleware.py
  requirements.txt
Labels: feature

#11 Improve Dockerfile Configuration and Add Health Check Functionality
  Dockerfile
  utils/entrypoint.sh
Labels: feature

#13 Env 설정
  config/settings.py
Labels: feature

#14 DJANGO_SETTINGS_MODULE env 버그 수정
  config/asgi.py
Labels: bug

#15 Chat_service 리팩토링
  chat_app/consumers.py
  chat_app/serializers.py
  chat_app/services.py
  chat_app/views.py
Labels: refactoring

#16 Chat 메시지에 user_avatar 추가
  chat_app/consumers.py
  config/services.py
Labels: feature

#17 Allowed hosts & install psycopg
  config/settings.py
  requirements.txt
Labels: feature

#18 Python 버전 수정 및 PostgreSQL 클라이언트 설치, API Gateway 요청 제한 설정
  Dockerfile
  config/settings.py
  requirements.txt
Labels: feature
